sudo: false
language: node_js
node_js:
  - 6
  - 7
  - 8
  - stable

cache:
  bundle: true
  directories:
    - node_modules

install:
  - npm install

jobs:
  include:
    - stage: Document deploy
      allow_failure: true
      script: npm run site
      deploy:
        edge:
          branch: v1.8.47
        provider: pages
        skip_cleanup: true
        github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
        local_dir: _site
